### DISCUSSION TITLE
Syntax for data validation framework

### DISCUSSION THREAD

**Discussion by sf-dcp** [NYCPlanning/data-engineering#902] [General]
## What
We will be implementing one data validation framework using `pandera` in `ingest` & `distribution`. The goal of this discussion is to agree on a syntax we will be using in metadata and recipe template yaml files when defining data checks. 

## Common tests
From my research, most common tests we will be using at ingest and packaging stages are: 
* **schema level**:
    *  row count
    * unique records with a combination of columns (as seen in `dbt`)

* **column level**:
    * data type
    * not null
    * unique
    * values in a given set
    * geometry type (i.e. point, polygon, etc)
    * geometry projection
    * numeric values range

## Requirements for syntax: 
* Readable. This will allow cross-team collaboration 
* Integrates with existing metadata syntax
* Similar to `dbt` test syntax, so that we just need to know 1 syntax that could be used everywhere.  `dbt` test [syntax](https://docs.getdbt.com/reference/resource-properties/data-tests#test_name):
    ``` yaml
  - name: <column_name>
      tests:
        - <test_name>
        - <test_name>:
          <argument_name>: <argument_value>
          config:
            <test_config>: <config-value> 
    ```

## Proposed syntax
Combing existing metadata syntax + `dbt` syntax, I'm proposing something like this:

```yaml
schema:
  tests:
    - row_count:
        above: 0
    - unique_combination_of_columns:
        combination_of_columns:
          - name
          - wkb_geometry

columns:
  - name: borough
    description: borough name
    data_type: string # could be standard or custom data type like bbl or point
    example: MANHATTAN
    tests:
      - not_null

      - unique

      - is_epsg_2263

      - accepted_values:
        values: ["MANHATTAN", "BROOKLYN"]
        description: this is description for check
        config:
          severity: warn

      - accepted_range:
        min_value: 0
        max_value: 100
```
