### ISSUE TITLE
dcpy user configuration

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#1555]
I figure for a first pass, use pyproject.toml or another type of config file, but since we use it pyproject.toml already this seems like a decent path. But this issue is meant to be a bit of a brainstorming space

sqlfluff has a lot of nice logic around how you might go about this just in terms of reading in a config, especially around looking for different files at different paths - see [here](https://github.com/sqlfluff/sqlfluff/blob/2004faf0145f7c894bac6994a88ff0faa499aa7b/src/sqlfluff/core/config/loader.py#L114)

But we could do something simpler to start - just assume that `pyproject.toml` is in the current folder or something for now. Basically, for ingest-related stuff, I'm thinking something like this

```toml
[tools.dcpy.lifecycle.connectors]
recipes.datasets = { conn_type = "s3", prefix = "datasets" }
ingest = { conn_type = "ingest_datastore", storage = "recipes.datasets" }
```

and then we'd have something in python
```python
config = config_from_toml("pyproject.toml")
...
connectors = ConnectorRegistry()
...
for connector in config["lifecycle"]["connectors"]:
    connectors.register(Connector(**connector))
```

this is clearly a little ugly as is, but something along these lines.
